config/routes.rb
TodoList::Application.routes.draw do


  

  get "static_pages/home"

  devise_for :users ,:controllers => { :sessions => "sessions" }

  devise_for :users do
    #Authentication
    get 'signin',  to: 'sessions#new', :as=>:new_user_session
    delete 'signout' => 'sessions#destroy', :as => :destroy_user_session
  end
  resources :users

  resources :tasks

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'static_pages#home'
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :due_date, :name, :priority, :user_id
  belongs_to :user
  validates_presence_of :due_date, :name

  def self.tasks_expired(u)
  	where("user_id= ? and due_date ='#{Date.today}'",u)

  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name
  validates_presence_of :first_name, :last_name, :email
  validates_uniqueness_of    :email,     :case_sensitive => false, :allow_blank => true, :if => :email_changed?
  validates_format_of :email, :with  => Devise.email_regexp, :allow_blank => true, :if => :email_changed?
  validates_presence_of   :password, :on=>:create
  validates_confirmation_of   :password, :on=>:create
  validates_length_of :password, :within => Devise.password_length, :allow_blank => true

  #Relations
  has_many :tasks, :dependent=>:destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  def new
    render :layout => 'signin_layout'
  end

  def create
    self.resource = warden.authenticate!(auth_options)
    if is_navigational_format?
      sign_in(resource_name, resource)
      redirect_to root_url, :flash => { :success => "Welcome #{current_user.first_name}" } 
    else
      flash.now[:error] = "Email/password incorrect.Try again"    
      render action: "new", :layout => 'signin_layout'
    end
  end

  def destroy
    redirect_path = root_url
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message :notice, :signed_out if signed_out && is_navigational_format?

    # We actually need to hardcode this as Rails default responder doesn't
    # support returning empty response on GET request
    respond_to do |format|
      format.any(*navigational_formats) { redirect_to redirect_path }
      format.all do
        head :no_content
      end
    end
  end

  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  respond_to :js, :json, :html
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])
    @task.user_id = current_user.id
    if @task.save
      flash[:success] = 'Task was successfully created.'
    else
      flash[:success] = 'Errors occurs while saving task.'
    end
    
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    if @task.update_attributes(params[:task])
      flash[:success] = 'Task was successfully updated.'
      redirect_to tasks_path
    else
      flash[:success] = 'Errors occurs while saving task.'
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  Application test for Linden
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="btn-group pull-right">
        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
          <i class="icon-user"></i> <%= current_user.first_name.gsub(/^([a-z])/) { $1.capitalize } if current_user%>
          <span class="caret"></span>
        </a>    
        <ul class="dropdown-menu">
          <li><%= link_to "Logout", "signout", method: "delete" %></li>
        </ul>    
      </div>
      <div class="nav-collapse">
        
        <ul class="nav">
          <li class="<%=(yield(:home))%>"><a href="/">Inicio</a></li>          
          <li class="<%=(yield(:task))%>"><a href="/tasks">Tasks</a></li>
        </ul>
          
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>

  <title>TODO List</title>
	<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
  <meta charset='utf-8'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= yield :head %>
</head>
<body>
  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
<!-- Top navigation bar -->
<%= render 'layouts/header' %>

<div class="container">
  <!-- Loading Div -->
  <div id="cargando" class="loadingdiv">
    <label id="textLoading"></label>
  </div>
  <div class="row">
    <div class="">
          <% flash.each do |name, msg| %>
            <div class="alert alert-<%= name %>">
              <a class="close" data-dismiss="alert">×</a>
              <%= msg %>
            </div>
          <% end %>
        <%= yield %>
    </div>
  </div>
  <%= render 'layouts/footer' %>
</div>
  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/layouts/signin_layout.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>

  <title>TODO List</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Le styles -->
  <style type="text/css">
    /* Override some defaults */
    html, body {
      background-color: #eee;
    }
    body {
      padding-top: 40px; 
    }
    .container {
      width: 300px;
    }

    /* The white background content wrapper */
    .container > .content {
      background-color: #fff;
      padding: 20px;
      margin: 0 -20px; 
      -webkit-border-radius: 10px 10px 10px 10px;
         -moz-border-radius: 10px 10px 10px 10px;
              border-radius: 10px 10px 10px 10px;
      -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);
         -moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);
              box-shadow: 0 1px 2px rgba(0,0,0,.15);
    }

    .login-form {
      margin-left: 65px;
    }
  
    legend {
      margin-right: -50px;
      font-weight: bold;
      color: #404040;
    }

  </style>
</head>
<body>
  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->

  <div class="container">
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name %>">
          <a class="close" data-dismiss="alert">×</a>
          <%= msg %>
        </div>
      <% end %>
      <div class="content">          
          <div class="row">
            <%= yield %>
          </div>
      </div>
  </div> <!-- /container -->
  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/static_pages/home.html.erb
<h1>Tasks TODO today <%= current_user.first_name %></h1>

<table class="table span12">
	<tr>
		<th>Due Date</th>
		<th>Name</th>
		<th>Priority</th>
	</tr>
	<% Task.tasks_expired(current_user.id).each do |task| %>
	<tr>
		<td><%= task.due_date.strftime("%d/%m/%Y")%> </td>
		<td><%= task.name%> </td>
		<td><%= task.priority%> </td>
	<% end %>
</table>

app/views/tasks/_form.html.erb
<%= simple_form_for @task.nil? ? Task.new : @task, :url => url_for(:action => 'create', :controller => 'tasks'), :html=>{:remote=>true, :id=>"new-task-form"} do |f| %>


  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :priority %>
    <%= f.input :due_date, :label=>"Due Date", :wrapper=>:prepend do %>
      <span class="add-on"><i class="icon-calendar"></i></span>
      <%= f.input_field :due_date, :as=>:string, :class=>"datepicker input-small"%> 
    <% end %>         
  </div>


<% end %>

app/views/tasks/edit.html.erb
<legend>Edit Task</legend>
<%= simple_form_for @task do |f| %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :priority %>
    <%= f.input :due_date, :label=>"Due Date", :wrapper=>:prepend do %>
      <span class="add-on"><i class="icon-calendar"></i></span>
      <%= f.input_field :due_date, :as=>:string, :class=>"datepicker input-small"%> 
    <% end %>         
  </div>
   <div class="form-actions">
	    <%= f.button :submit, :class => 'btn-primary', :value => 'Guardar' %>
	    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
	        tasks_path, :class => 'btn' %>
   </div>


<% end %>

app/views/tasks/index.html.erb
<legend>Listing tasks</legend>
<div class="row">
<div id="tasks" class="span7">
<table class="table">
  <tr>
    <th>Name</th>
    <th>Priority</th>
    <th>Due date</th>
    <th></th>
    <th></th>
  </tr>

<% current_user.tasks.where.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.priority %></td>
    <td><%= task.due_date %></td>
    <td><%= link_to 'Edit', edit_task_path(task),{'data-toggle'=>'modal'} %></td>
    <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
</div>
</div>

<a href="#task-form" class="btn btn-primary btn-small" data-toggle="modal" >New task </a>

<!-- Modal Form for New Task -->
<div class="modal hide fade" id="task-form">
  <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h3>New Task</h3>
    </div>
    <div class="modal-body">
      <%= render "form" %>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal" aria-hidden="true">Cerrar</a>
      <a href="#" onclick="$('#new-task-form').submit()" class="btn btn-primary">Aceptar</a>
    </div>
  
</div>

app/views/tasks/new.html.erb
<% provide(:task, 'active') %>
<Legend>New task</legend>
<%= render 'form' %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Priority:</b>
  <%= @task.priority %>
</p>

<p>
  <b>Due date:</b>
  <%= @task.due_date %>
</p>

<p>
  <b>User:</b>
  <%= @task.user_id %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>